export const images = [
    {
      id: 1,
      src: "/images/1.png",
      title: "Smart Touch Switches",
      // desc: "Capacitive Touch ,	Touch / Voice / App ,	Operating using WIFI, 2.4GHz,	Overload protection ,	Modular design – 4M, 8M,12M ,	Panel Mirroring,	Built,in RTC ",
      desc: "-	Capacitive Touch",
      desc1:"-	Touch / Voice / App",
      desc2:"-  Operating using WIFI",
      desc3:"-	Overload protection ",
      desc4:"-	Modular design – 4M, 8M,12M",
      desc5:"-	Panel Mirroring ",
    },
    {
      id: 2,
      src: "/images/2.png",
      title: "Scene Switches",
      desc: "-	Capacitive Touch",
      desc1:"-	Touch / Voice / App",
      desc2:"- 	Operating using WIFI, 2.4GHz",
      desc3:"-	Overload protection  ",
      desc4:"-	Modular design ",
      desc5:"-	Customisable front skin & touch design ",
      
    },
    {
      id: 3,
      src: "/images/3.png",
      title: "Smart Lighting",
      // desc: "Espresso is a concentrated form of coffee, served in shots. It's made of two ingredients , finely ground, 100% coffee, and hot water.",
      desc: "-	Human centric lighting (HCL)",
      desc1:"-	Touch / Voice / App",
      desc2:"-	Tunable white technology",
      desc3:"-	Single interface to control multiple lights",
      desc4:"-	Operating using WIFI, 2.4GHz",
      desc5:" ",
     
    },
    {
      id: 4,
      src: "/images/4.png",
      title: "Smart Curtain & Blind",
      // desc: "A latte or caffè latte is a milk coffee that boasts a silky layer of foam as a real highlight to the drink. A true latte will be made up of one or two shots of espresso, steamed milk and a final, thin layer of frothed milk on top",
      desc: "-  Touch / Voice / App / Remote operated",
      desc1:"-	AC operated Motor ",
      desc2:"-	Single / Two direction – configurable",
      desc3:"-	Supply include Motor, Track/pipe, Touch switch, Mob app",
      desc4:"-	More than 20 ft. also possible",
      desc5:"-  Fabric weight can be 80-100 Kgs ",
    },
    {
      id: 5,
      src: "/images/5.png",
      title: "Smart Door Lock",
      // desc: "Caffè macchiato, sometimes called espresso macchiato, is an espresso coffee drink with a small amount of milk, usually foamed. ",
      desc: "-  5 modes of operation Biometric / Mobile Phone/ Manual Key/ PIN code/ RFID card ",
      desc1:"-	Two Versions – Standard & Premium",
      desc2:"-	1 Latch bolt & 3 Deadbolts for more security",
      desc3:"-	100 Passcode & 100 Finger prints",
      desc4:"-	Wrong access alarm",
      desc5:"-  Scheduler & Temporary PIN access ",
   
    },
  ];
  